services:
  frontend_dev:
    image: $WERF_FRONTEND_DEV_DOCKER_IMAGE_NAME
    profiles: [dev]
    volumes:
      - .:/workspace
      - vscode:/app/.vscode-server
      - $HOME/.ssh/id_rsa:/app/.ssh/id_rsa
    working_dir: /workspace
    ports:
      - 8080:8080
volumes:
  vscode:
