services:
  frontend_dev:
    image: $WERF_FRONTEND_DEV_DOCKER_IMAGE_NAME
    profiles: [dev]
    volumes:
      - ./frontend:/workspace
      - vscode:/root/.vscode-server
    working_dir: /workspace
    ports:
      - 8080:8080
volumes:
  vscode:
